exp: TextClassification
mode: 
    - train
    
models: 
    hf_text_classification_model:
        - distilbert-base-uncased

          
trainfpath: /home/eheng/NLPScholarFork/final_project/finalproject_sample_dataset.tsv
validfpath: /home/eheng/NLPScholarFork/final_project/finalproject_sample_dataset.tsv
modelfpath: /home/eheng/NLPScholarFork/final_project/finalproject_sample_trained_model
loadPretrained: False
numLabels: 4